### ISSUE TITLE
Remove xView2 from dataset distribution

### ISSUE THREAD

**Issue by RitwikGupta** [The-AI-Alliance/GEO-Bench-VLM#1]
Hi,

I'm sorry to put this issue in, but legal constraints around the xBD dataset prohibit open re-distribution of the dataset. Please take down the portions of GeoBench-VLM that are images and labels from xBD. Instead, please ask GeoBench-VLM users to download xBD directly from our website and provide users a script to transform that data into your format.

Apologies, but these are constraints placed on the dataset by the U.S. Government.

Thanks,
Ritwik (xBD author)

**Comment by RitwikGupta** [comment]
People are not allowed to download the dataset unless they agree to the xView2 terms and conditions (https://xview2.org/terms) that they must attest to during account registration.

**Comment by msohaildanish** [comment]
Thank you for raising this issue. We have updated the benchmark on HuggingFace by removing the xBD images. We are releasing a script that users can use to download the xBD dataset directly from the xView2 website and transform it into the required format for the benchmark.
